#!/usr/bin/env bash
# gen-third-party-notices.sh
#
# Regenerates THIRD_PARTY_NOTICES.md (LIC-001): the bundled license texts for
# every third-party Go module actually linked into the shipped binaries
# (the build dependencies of ./cmd/...), plus a notice for the vendored ATR
# ruleset. Run this after changing dependencies:
#
#     ./scripts/gen-third-party-notices.sh
#
# The file it writes is committed and shipped alongside every release
# artifact so downstream users receive the required attribution.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

out="THIRD_PARTY_NOTICES.md"
mc="$(go env GOMODCACHE)"

# The set of modules linked into the shipped binaries. Excludes this module
# and any test-only / build-time-codegen dependency (e.g. golang-lru, pulled
# in only by modernc.org/sqlite's build-time gc/v3 codegen toolchain and NOT
# present in the runtime link — verified via `go list -deps ./cmd/...`).
modules="$(go list -deps -f '{{if .Module}}{{.Module.Path}}@{{.Module.Version}}{{end}}' ./cmd/... \
  | sort -u | grep -v '^github.com/malanta-ai/')"

{
  echo "# Third-Party Notices"
  echo
  echo "Malanta TrustGate is distributed with the third-party Go modules"
  echo "listed below, each linked into the shipped hook binaries and the"
  echo "\`trustgate\` CLI. Their license texts are reproduced verbatim. This"
  echo "file is generated by \`scripts/gen-third-party-notices.sh\` from the"
  echo "resolved module graph of \`./cmd/...\`; do not edit it by hand."
  echo
  echo "> Note on \`golang.org/x/net\`: it bundles the Public Suffix List in"
  echo "> \`x/net/publicsuffix\`, whose embedded data is under MPL-2.0 while"
  echo "> the surrounding Go code is BSD-3-Clause. See that package for"
  echo "> details."
  echo
  echo "---"
  echo
  while IFS= read -r m; do
    [ -z "$m" ] && continue
    dir="$mc/$m"
    lf="$(ls "$dir" 2>/dev/null | grep -iE '^(license|licence|copying|notice)' | head -1 || true)"
    echo "## $m"
    echo
    if [ -n "$lf" ] && [ -f "$dir/$lf" ]; then
      echo '```'
      cat "$dir/$lf"
      echo '```'
    else
      echo "_No license file found in the module cache; consult the module's"
      echo "upstream repository for its license terms._"
    fi
    echo
    echo "---"
    echo
  done <<< "$modules"

  # Explicit MPL-2.0 disclosure for the embedded Public Suffix List data.
  # golang.org/x/net/publicsuffix's Go code is BSD-3-Clause (covered by the
  # x/net LICENSE above), but the embedded PSL data it compiles in
  # (publicsuffix/data/*) is sourced from publicsuffix.org and is licensed
  # MPL-2.0. That data is linked into the shipped binaries (eTLD+1
  # reduction in internal/extract and internal/reputation), so we disclose
  # it explicitly.
  echo "## Public Suffix List data (MPL-2.0)"
  echo
  echo "The shipped binaries embed the Public Suffix List via"
  echo "\`golang.org/x/net/publicsuffix\` (used for eTLD+1 reduction). The"
  echo "PSL **data** originates from https://publicsuffix.org/ and is"
  echo "licensed under the **Mozilla Public License 2.0 (MPL-2.0)**."
  echo
  echo "- We distribute this data **unmodified**; no MPL-covered file is"
  echo "  altered by this project."
  echo "- Source form of the MPL-covered data is publicly available at"
  echo "  https://github.com/publicsuffix/list and"
  echo "  https://publicsuffix.org/list/ ."
  echo "- Full MPL-2.0 license text: https://www.mozilla.org/MPL/2.0/ ."
  echo
  echo "MPL-2.0 is a file-level (weak) copyleft license: it applies to the"
  echo "covered files only and does not extend to the rest of this"
  echo "otherwise MIT-licensed project."
  echo
  echo "---"
  echo

  # Vendored ATR ruleset (not a Go module — see internal/atr/rules and
  # scripts/sync-atr-rules.py). Upstream is the agent-threat-rules project.
  echo "## Agent Threat Rules (vendored ruleset)"
  echo
  echo "\`internal/atr/rules/\` contains a base64-obfuscated snapshot of the"
  echo "upstream \`agent-threat-rules\` project (https://agentthreatrule.org),"
  echo "refreshed via \`scripts/sync-atr-rules.py\`. The upstream ruleset is"
  echo "distributed under the MIT License; its copyright is retained by the"
  echo "agent-threat-rules authors. See the upstream project for the full"
  echo "license text and attribution."
  echo
} > "$out"

echo "Wrote $out ($(grep -c '^## ' "$out") sections)."
